services:
  - type: worker
    name: anonymizer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python anonymizer.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
